Repository hoptical/grafana-kafka-datasource, pull requests merged in 2025-04, with the labels that each got.

#58 Add/redpanda console
  docker-compose.yaml
  example/python/README.md
Labels: enhancement

#57 Change Kafka driver
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Magefile.go
  README.md
  go.mod
  go.sum
  pkg/kafka_client/client.go
  pkg/plugin/plugin.go
  src/ConfigEditor.tsx
  src/types.ts
Labels: bug

#60 Add/golang example
  .gitignore
  README.md
  example/README.md
  example/go/producer.go
  example/python/README.md
  example/python/producer.py
Labels: documentation, enhancement

#61 Fix switch component
  src/QueryEditor.tsx
Labels: bug

#62 Update/grafana go sdk
  .github/workflows/ci.yml
  go.mod
  go.sum
  pkg/plugin/plugin.go
Labels: enhancement

#63 add value-offset to go producer example
  example/go/producer.go
Labels: enhancement
